#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

wmake $targetType mixtureViscosityModels
wmake $targetType relativeVelocityModels
wmake $targetType sherwoodModels
wmake $targetType coverageModels
wmake $targetType massAndSpeciesTransferModels
wmake $targetType concentrationLossModels
wmake $targetType

#------------------------------------------------------------------------------
